{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 136,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "import pandas as pd\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from skopt import gp_minimize\n",
    "from skopt.space import Integer\n",
    "from numpy import mean\n",
    "from skopt.utils import use_named_args\n",
    "from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, explained_variance_score, median_absolute_error\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "#\n",
    "from sklearn.tree import DecisionTreeRegressor\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "dataset = pd.read_csv('./Dataset/dataset.csv')\n",
    "# \n",
    "features = [\"Freq\"]\n",
    "targets = [\"W\", \"L\", \"Lf\"]\n",
    "x = dataset[features]\n",
    "y = dataset[targets]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Split\n",
    "x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)\n",
    "\n",
    "# Scaling\n",
    "scaler = StandardScaler()\n",
    "x_train_scaled = scaler.fit_transform(x_train)\n",
    "x_test_scaled = scaler.transform(x_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 139,
   "metadata": {},
   "outputs": [],
   "source": [
    "search_space = [Integer(1, 999999999999999, name='max_depth'), Integer(2, 999999999999999, name='min_samples_split')]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "@use_named_args(search_space)\n",
    "def evaluate_model(**params):\n",
    "    model = DecisionTreeRegressor(max_depth=params['max_depth'], min_samples_split=params['min_samples_split'])\n",
    "    model.fit(x_train_scaled, y_train)\n",
    "    y_pred = model.predict(x_test_scaled)\n",
    "    error = mean((y_test - y_pred) ** 2)  # MSE\n",
    "    return error"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 141,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\optimizer\\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [1, 2]\n",
      "  warnings.warn(\n",
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\skopt\\space\\transformers.py:267: RuntimeWarning: invalid value encountered in cast\n",
      "  return np.round(X_orig).astype(int)\n"
     ]
    }
   ],
   "source": [
    "result = gp_minimize(evaluate_model, search_space)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 142,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>#sk-container-id-12 {color: black;background-color: white;}#sk-container-id-12 pre{padding: 0;}#sk-container-id-12 div.sk-toggleable {background-color: white;}#sk-container-id-12 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-12 label.sk-toggleable__label-arrow:before {content: \"▸\";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-12 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-12 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-12 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-12 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-12 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-12 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: \"▾\";}#sk-container-id-12 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-12 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-12 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-12 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-12 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-12 div.sk-parallel-item::after {content: \"\";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-12 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-12 div.sk-serial::before {content: \"\";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-12 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-12 div.sk-item {position: relative;z-index: 1;}#sk-container-id-12 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-12 div.sk-item::before, #sk-container-id-12 div.sk-parallel-item::before {content: \"\";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-12 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-12 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-12 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-12 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-12 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-12 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-12 div.sk-label-container {text-align: center;}#sk-container-id-12 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-12 div.sk-text-repr-fallback {display: none;}</style><div id=\"sk-container-id-12\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>DecisionTreeRegressor(max_depth=2100629544)</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-12\" type=\"checkbox\" checked><label for=\"sk-estimator-id-12\" class=\"sk-toggleable__label sk-toggleable__label-arrow\">DecisionTreeRegressor</label><div class=\"sk-toggleable__content\"><pre>DecisionTreeRegressor(max_depth=2100629544)</pre></div></div></div></div></div>"
      ],
      "text/plain": [
       "DecisionTreeRegressor(max_depth=2100629544)"
      ]
     },
     "execution_count": 142,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "best_max_depth = result.x[0]\n",
    "best_min_samples_split = result.x[1]\n",
    "best_model = DecisionTreeRegressor(max_depth=best_max_depth, min_samples_split=best_min_samples_split)\n",
    "best_model.fit(x_train_scaled, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\sachxn\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\sklearn\\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "582"
      ]
     },
     "execution_count": 143,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#\n",
    "new_dataset = pd.read_csv('./Dataset/paraS.csv')  # \n",
    "new_data = new_dataset[\"Freq\"].values.reshape(-1, 1)  # \n",
    "\n",
    "# Scaling \n",
    "new_data_scaled = scaler.transform(new_data)\n",
    "\n",
    "# \n",
    "y_pred = best_model.predict(x_test_scaled)\n",
    "y_pred.size\n",
    "# df_y_pred = pd.DataFrame(y_pred)\n",
    "# df_y_pred.to_csv('y_pred.csv',index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Best Accuracy: 0.994\n",
      "Best Parameters: max_depth=2100629544, min_samples_split=2\n",
      "Predictions: [[ 25.57  19.58  11.52]\n",
      " [ 49.26  38.29  22.19]\n",
      " [109.6   85.72  49.4 ]\n",
      " [ 38.36  29.7   17.28]\n",
      " [ 25.47  19.5   11.47]\n",
      " [ 17.18  12.9    7.74]\n",
      " [ 26.86  20.61  12.1 ]\n",
      " [ 44.85  34.82  20.21]\n",
      " [ 29.41  22.62  13.25]\n",
      " [ 43.23  33.54  19.48]\n",
      " [ 38.79  30.03  17.47]\n",
      " [100.7   78.69  45.36]\n",
      " [ 35.5   27.44  15.99]\n",
      " [ 39.19  30.35  17.65]\n",
      " [ 24.72  18.91  11.14]\n",
      " [ 95.22  74.4   42.9 ]\n",
      " [ 27.12  20.81  12.22]\n",
      " [ 37.76  29.22  17.01]\n",
      " [ 28.03  21.53  12.63]\n",
      " [ 25.52  19.54  11.5 ]\n",
      " [ 49.85  38.75  22.46]\n",
      " [ 35.36  27.33  15.93]\n",
      " [ 17.36  13.05   7.82]\n",
      " [ 17.13  12.86   7.72]\n",
      " [ 51.48  40.04  23.19]\n",
      " [ 16.6   12.44   7.48]\n",
      " [ 34.01  26.27  15.32]\n",
      " [107.6   84.09  48.46]\n",
      " [103.4   80.84  46.59]\n",
      " [ 18.01  13.57   8.11]\n",
      " [ 34.4   26.57  15.5 ]\n",
      " [ 38.46  29.78  17.33]\n",
      " [ 93.28  72.87  42.02]\n",
      " [ 44.76  34.75  20.16]\n",
      " [ 51.19  39.81  23.06]\n",
      " [ 15.89  11.87   7.16]\n",
      " [111.2   86.97  50.12]\n",
      " [104.6   81.17  47.13]\n",
      " [ 49.31  38.33  22.22]\n",
      " [ 41.47  32.15  18.68]\n",
      " [ 35.58  27.5   16.03]\n",
      " [ 25.34  19.4   11.42]\n",
      " [ 36.75  28.43  16.56]\n",
      " [ 27.49  21.11  12.38]\n",
      " [ 42.16  32.69  18.99]\n",
      " [ 28.72  22.08  12.94]\n",
      " [ 53.22  41.41  23.98]\n",
      " [ 29.33  22.56  13.21]\n",
      " [ 28.85  22.18  13.  ]\n",
      " [ 37.08  28.69  16.71]\n",
      " [ 44.2   34.3   19.91]\n",
      " [ 48.06  37.35  21.65]\n",
      " [ 33.94  26.21  15.29]\n",
      " [ 16.47  12.33   7.42]\n",
      " [ 25.13  19.23  11.32]\n",
      " [ 25.27  19.34  11.38]\n",
      " [ 27.64  21.22  12.45]\n",
      " [ 16.63  12.46   7.49]\n",
      " [ 35.83  27.7   16.14]\n",
      " [ 18.19  13.71   8.19]\n",
      " [ 28.24  21.7   12.72]\n",
      " [110.7   86.55  49.87]\n",
      " [ 37.98  29.4   17.11]\n",
      " [ 25.16  19.25  11.33]\n",
      " [ 25.67  19.66  11.56]\n",
      " [ 26.81  20.57  12.07]\n",
      " [ 51.71  40.22  23.3 ]\n",
      " [ 44.59  34.61  20.09]\n",
      " [ 26.12  20.02  11.77]\n",
      " [ 17.94  13.51   8.08]\n",
      " [ 27.88  21.41  12.56]\n",
      " [ 27.54  21.15  12.41]\n",
      " [ 37.85  29.3   17.05]\n",
      " [ 42.91  33.29  19.33]\n",
      " [102.    79.75  45.97]\n",
      " [ 35.19  27.2   15.85]\n",
      " [ 25.61  19.61  11.54]\n",
      " [ 26.55  20.36  11.96]\n",
      " [ 94.43  73.78  42.54]\n",
      " [ 48.99  38.08  22.07]\n",
      " [ 16.89  12.67   7.61]\n",
      " [ 36.58  28.29  16.48]\n",
      " [ 28.54  21.94  12.86]\n",
      " [ 29.39  22.61  13.24]\n",
      " [ 52.73  41.02  23.76]\n",
      " [ 26.18  20.07  11.79]\n",
      " [100.    78.17  45.06]\n",
      " [ 34.32  26.51  15.46]\n",
      " [ 17.41  13.08   7.84]\n",
      " [ 27.61  21.2   12.44]\n",
      " [ 27.85  21.39  12.54]\n",
      " [ 27.98  21.49  12.6 ]\n",
      " [ 48.27  37.51  21.74]\n",
      " [ 36.29  28.06  16.35]\n",
      " [ 52.01  40.45  23.43]\n",
      " [ 25.52  19.54  11.5 ]\n",
      " [ 16.17  12.1    7.28]\n",
      " [ 26.35  20.2   11.87]\n",
      " [ 37.76  29.22  17.01]\n",
      " [102.7   80.29  46.28]\n",
      " [ 36.58  28.29  16.48]\n",
      " [ 25.42  19.47  11.45]\n",
      " [ 50.29  39.1   22.66]\n",
      " [ 17.99  13.55   8.11]\n",
      " [ 44.28  34.37  19.95]\n",
      " [ 16.74  12.55   7.54]\n",
      " [ 37.39  28.93  16.84]\n",
      " [ 37.51  29.03  16.9 ]\n",
      " [ 25.93  19.87  11.68]\n",
      " [ 27.21  20.89  12.26]\n",
      " [ 43.9   34.07  19.78]\n",
      " [ 43.52  33.77  19.61]\n",
      " [ 28.81  22.15  12.98]\n",
      " [ 29.15  22.41  13.13]\n",
      " [ 16.45  12.32   7.41]\n",
      " [ 48.58  37.75  21.88]\n",
      " [ 28.65  22.02  12.91]\n",
      " [ 26.    19.93  11.71]\n",
      " [ 36.49  28.22  16.44]\n",
      " [ 51.77  40.27  23.32]\n",
      " [ 49.96  38.84  22.51]\n",
      " [ 28.3   21.74  12.75]\n",
      " [ 49.15  38.2   22.14]\n",
      " [ 26.93  20.66  12.13]\n",
      " [ 37.66  29.15  16.97]\n",
      " [109.6   85.72  49.4 ]\n",
      " [ 16.39  12.27   7.38]\n",
      " [ 24.8   18.97  11.18]\n",
      " [ 15.93  11.91   7.18]\n",
      " [ 24.92  19.07  11.23]\n",
      " [ 25.75  19.73  11.6 ]\n",
      " [ 52.01  40.45  23.43]\n",
      " [111.8   87.4   50.37]\n",
      " [ 42.31  32.81  19.06]\n",
      " [109.1   85.3   49.16]\n",
      " [ 16.96  12.72   7.64]\n",
      " [ 16.26  12.17   7.33]\n",
      " [ 36.7   28.38  16.53]\n",
      " [ 34.09  26.33  15.36]\n",
      " [ 26.81  20.57  12.07]\n",
      " [ 18.19  13.71   8.19]\n",
      " [ 28.24  21.7   12.72]\n",
      " [ 16.09  12.03   7.25]\n",
      " [ 26.72  20.49  12.04]\n",
      " [ 16.45  12.32   7.41]\n",
      " [ 17.13  12.86   7.72]\n",
      " [ 27.09  20.78  12.2 ]\n",
      " [ 16.53  12.38   7.44]\n",
      " [ 37.63  29.12  16.95]\n",
      " [ 28.38  21.81  12.79]\n",
      " [ 16.99  12.75   7.65]\n",
      " [ 94.43  73.78  42.54]\n",
      " [ 17.02  12.77   7.67]\n",
      " [ 17.05  12.8    7.68]\n",
      " [ 33.81  26.11  15.23]\n",
      " [ 27.93  21.45  12.58]\n",
      " [ 51.31  39.9   23.11]\n",
      " [ 36.2   27.99  16.31]\n",
      " [ 26.12  20.02  11.77]\n",
      " [113.2   88.49  50.99]\n",
      " [ 44.5   34.54  20.05]\n",
      " [ 25.71  19.69  11.58]\n",
      " [ 36.9   28.55  16.62]\n",
      " [ 53.6   41.7   24.15]\n",
      " [ 93.66  73.17  42.19]\n",
      " [ 17.89  13.47   8.06]\n",
      " [ 44.03  34.17  19.84]\n",
      " [ 17.07  12.81   7.69]\n",
      " [ 45.39  35.24  20.44]\n",
      " [ 34.95  27.01  15.75]\n",
      " [ 25.05  19.17  11.28]\n",
      " [ 35.28  27.26  15.89]\n",
      " [ 38.36  29.7   17.28]\n",
      " [ 44.67  34.68  20.13]\n",
      " [ 29.05  22.34  13.09]\n",
      " [108.3   84.69  48.81]\n",
      " [ 35.83  27.7   16.14]\n",
      " [113.2   88.49  50.99]\n",
      " [ 93.66  73.17  42.19]\n",
      " [ 35.63  27.55  16.05]\n",
      " [ 52.55  40.88  23.67]\n",
      " [ 16.68  12.5    7.51]\n",
      " [ 25.97  19.9   11.7 ]\n",
      " [ 94.24  73.63  42.46]\n",
      " [ 45.52  35.34  20.51]\n",
      " [ 97.05  75.83  43.72]\n",
      " [ 25.67  19.66  11.56]\n",
      " [ 26.66  20.44  12.01]\n",
      " [ 26.5   20.32  11.94]\n",
      " [ 16.03  11.98   7.22]\n",
      " [106.6   83.3   48.01]\n",
      " [ 50.85  39.54  22.91]\n",
      " [ 35.91  27.77  16.18]\n",
      " [ 42.43  32.91  19.11]]\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "582"
      ]
     },
     "execution_count": 144,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "print('Best Accuracy: %.3f' % (1.0 - result.fun))\n",
    "print('Best Parameters: max_depth=%d, min_samples_split=%d' % (result.x[0], result.x[1]))\n",
    "\n",
    "# \n",
    "\n",
    "print(\"Predictions:\", y_pred)\n",
    "y_pred.size\n",
    "# df_y_pred = pd.DataFrame(y_pred)\n",
    "# df_y_pred.to_csv('y_pred.csv',index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# FreqInput = float(input('Nhập vào tần số muốn dự đoán: '))\n",
    "FreqInput = 1.2\n",
    "# \n",
    "new_data = [[FreqInput]]\n",
    "\n",
    "# Scaling \n",
    "new_data_scaled = scaler.transform(new_data)\n",
    "\n",
    "# \n",
    "y_pred = best_model.predict(new_data_scaled)\n",
    "\n",
    "# \n",
    "print('Giá trị nhập vào là: ', FreqInput)\n",
    "print('Giá trị dự đoán:', y_pred)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                                             Metric  Gausians\n",
      "0                         Mean Absolute Error (MAE)  0.042534\n",
      "1                          Mean Squared Error (MSE)  0.006382\n",
      "2                    Root Mean Squared Error (RMSE)  0.079889\n",
      "3                                          R² Score  0.999985\n",
      "4                          Explained Variance Score  0.999985\n",
      "5                             Median Absolute Error  0.020000\n",
      "6                         Mean Bias Deviation (MBD)  0.010507\n",
      "7             Mean Absolute Percentage Error (MAPE)  0.103837\n",
      "8  Symmetric Mean Absolute Percentage Error (sMAPE)  0.103824\n"
     ]
    }
   ],
   "source": [
    "def regression_report(y_true, y_pred):\n",
    "    mae = mean_absolute_error(y_true, y_pred)\n",
    "    mse = mean_squared_error(y_true, y_pred)\n",
    "    rmse = np.sqrt(mse)\n",
    "    r2 = r2_score(y_true, y_pred)\n",
    "    explained_variance = explained_variance_score(y_true, y_pred)\n",
    "    median_ae = median_absolute_error(y_true, y_pred)\n",
    "\n",
    "    # Mean Bias Deviation (MBD)\n",
    "    mbd = np.mean(y_pred - y_true)\n",
    "\n",
    "    # Mean Absolute Percentage Error (MAPE)\n",
    "    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100\n",
    "\n",
    "    # Symmetric Mean Absolute Percentage Error (sMAPE)\n",
    "    smape = np.mean(2 * np.abs(y_pred - y_true) / (np.abs(y_true) + np.abs(y_pred))) * 100\n",
    "\n",
    "    report = pd.DataFrame({\n",
    "        'Metric': [\n",
    "            'Mean Absolute Error (MAE)',\n",
    "            'Mean Squared Error (MSE)',\n",
    "            'Root Mean Squared Error (RMSE)',\n",
    "            'R² Score',\n",
    "            'Explained Variance Score',\n",
    "            'Median Absolute Error',\n",
    "            'Mean Bias Deviation (MBD)',\n",
    "            'Mean Absolute Percentage Error (MAPE)',\n",
    "            'Symmetric Mean Absolute Percentage Error (sMAPE)'\n",
    "        ],\n",
    "        'Gausians': [mae, mse, rmse, r2, explained_variance, median_ae, mbd, mape, smape]\n",
    "    })\n",
    "\n",
    "    return report\n",
    "\n",
    "report = regression_report(y_test, y_pred)\n",
    "print(report)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
